kind: Secret
apiVersion: v1
metadata:
  name: {{ include "assemble-backstage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "assemble-backstage.labels" . | nindent 4 }}
stringData:
  rhsso.clientId: {{ required "RHSSO clientId must be provided" .Values.rhsso.clientId }}
  rhsso.clientSecret: {{ required "RHSSO clientSecret must be provided" .Values.rhsso.clientSecret }}
{{- if .Values.oauth.enabled }}
  oauth.cookieSecret: {{ default (randAlpha 32 | lower | b64enc) .Values.oauth.cookieSecret }}
{{- end }}
type: Opaque